# Copyright (c) 2019-2020-2021 Luca Cappa
# Released under the term specified in file LICENSE.txt
# SPDX short identifier: MIT
name: Build and test fdbox
on:
  push:
    braches:
      - main
      - github-actions

jobs:
  build-dos: 
    name: openwatcom-dos
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Build with ow
        working-directory: '${{ github.workspace }}'
        run : |
          cd etc
          ./build-ow.sh
          cd ..
          mkdir -p b/owdos
          mkdir -p a/owdos
          cp src/fdbox.exe b/owdos/
          cp src/tests.exe b/owdos/
          cp src/fdbox.exe a/owdos/
          cp src/tests.exe a/owdos/
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: fdbox-build-${{ steps.vars.outputs.sha_short }}
          path: '${{ github.workspace }}/b/'
      - name: Archive docs
        uses: actions/upload-artifact@v2.2.4
        with:
          name: fdbox-release-${{ steps.vars.outputs.sha_short }}
          path: '${{ github.workspace }}/a/'

  build-cmake:
    name: ${{ matrix.os }}-hosted-basic
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: windows-latest
            triplet: x64-windows
          - os: ubuntu-latest
            triplet: x64-linux
          - os: macos-latest
            triplet: x64-osx
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - uses: lukka/get-cmake@latest
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Install clang-tidy
        if: matrix.os == 'ubuntu-latest'
        run : sudo apt install clang-tidy
      - name: Confiure + build (CMake+Ninja)
        uses: lukka/run-cmake@v3.4
        id: runcmake
        with:
          cmakeGenerator: 'Ninja'
          cmakeListsOrSettingsJson: 'CMakeListsTxtBasic'
          cmakeListsTxtPath: '${{ github.workspace }}/CMakeLists.txt'
          buildWithCMakeArgs: '-- -v'
          buildDirectory: '${{ runner.workspace }}/b/${{ runner.os }}'
      - name: Run clang format
        if: matrix.os == 'ubuntu-latest'
        run : |
          ninja -C '${{ runner.workspace }}/b/${{ runner.os }}' clang-format 
          echo ninja -C '${{ runner.workspace }}/b/${{ runner.os }}' check-clang-format
      - name: Create release package
        working-directory: '${{ github.workspace }}'
        run : |
          mkdir -p '${{ github.workspace }}/a/${{ runner.os }}'
          cp ${{ runner.workspace }}/b/${{ runner.os }}/fdbox* '${{ github.workspace }}/a/${{ runner.os }}/'
          cp ${{ runner.workspace }}/b/${{ runner.os }}/tests* '${{ github.workspace }}/a/${{ runner.os }}/'
      - name: Run tests
        run : '${{ runner.workspace }}/b/${{ runner.os }}/tests'
      - name: Archive production artifacts
        uses: actions/upload-artifact@v2.2.4
        with:
          name: fdbox-build-${{ steps.vars.outputs.sha_short }}
          path: '${{ runner.workspace }}/b/'
      - name: Archive docs
        uses: actions/upload-artifact@v2.2.4
        with:
          name: fdbox-release-${{ steps.vars.outputs.sha_short }}
          path: '${{ github.workspace }}/a/'

  package-docs:
    name: package documentation
    runs-on: ubuntu-latest
    needs: build-cmake
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - name: Copy documentation
        working-directory: '${{ github.workspace }}'
        run : |
          mkdir -p a/
          cp readme.txt a/
          cp license.txt a/
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Archive docs
        uses: actions/upload-artifact@v2.2.4
        with:
          name: fdbox-release-${{ steps.vars.outputs.sha_short }}
          path: '${{ github.workspace }}/a/'
